import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { LenisProvider } from "@/components/lenis-provider";
import { AppProviders } from "@/components/providers/app-providers";

import "./globals.css";
import "lenis/dist/lenis.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppProviders>
          <LenisProvider>{children}</LenisProvider>
        </AppProviders>
      </body>
    </html>
  );
}
