/**
 * Keep in sync with `api-hr-io/authentication/company_email_policy.py` (PERSONAL_EMAIL_DOMAINS).
 */
export const PERSONAL_EMAIL_DOMAINS = new Set<string>([
  "aol.com",
  "aim.com",
  "att.net",
  "bk.ru",
  "list.ru",
  "inbox.ru",
  "mail.ru",
  "btinternet.com",
  "charter.net",
  "comcast.net",
  "daum.net",
  "duck.com",
  "email.com",
  "fastmail.com",
  "fastmail.fm",
  "freenet.de",
  "arcor.de",
  "gmail.com",
  "googlemail.com",
  "gmx.com",
  "gmx.de",
  "gmx.net",
  "gmx.at",
  "gmx.ch",
  "gmx.fr",
  "gmx.li",
  "gci.net",
  "hush.com",
  "hushmail.com",
  "hey.com",
  "hotmail.com",
  "hotmail.co.uk",
  "hotmail.de",
  "hotmail.fr",
  "hotmail.co.jp",
  "icloud.com",
  "me.com",
  "mac.com",
  "inbox.com",
  "live.com",
  "live.co.uk",
  "live.fr",
  "live.de",
  "live.nl",
  "live.ca",
  "mail.com",
  "msn.com",
  "naver.com",
  "nifty.com",
  "i.softbank.jp",
  "o2.de",
  "o2.pl",
  "outlook.com",
  "outlook.com.au",
  "outlook.com.br",
  "outlook.de",
  "outlook.fr",
  "outlook.co.uk",
  "outlook.jp",
  "pm.me",
  "protonmail.com",
  "protonmail.ch",
  "proton.me",
  "posteo.de",
  "posteo.net",
  "posteo.org",
  "qq.com",
  "163.com",
  "126.com",
  "sina.com",
  "sina.cn",
  "rediffmail.com",
  "rediff.com",
  "roadrunner.com",
  "rocketmail.com",
  "sbcglobal.net",
  "sbcglobal.com",
  "startmail.com",
  "t-online.de",
  "tuta.io",
  "tutanota.com",
  "tutanota.de",
  "tutamail.com",
  "tuta.com",
  "verizon.net",
  "web.de",
  "yahoo.com",
  "ymail.com",
  "yahoo.co.uk",
  "yahoo.fr",
  "yahoo.de",
  "yahoo.in",
  "yahoo.com.au",
  "yahoo.co.jp",
  "yahoo.ca",
  "yahoo.com.br",
  "yandex.com",
  "yandex.ru",
  "ya.ru",
  "yandex.ua",
  "yandex.kz",
  "yandex.by",
]);

const SUFFIXES = [
  "gmail.com",
  "googlemail.com",
  "outlook.com",
  "hotmail.com",
  "live.com",
  "yahoo.com",
  "ymail.com",
] as const;

export function isPersonalEmailDomain(domain: string): boolean {
  const d = domain.trim().toLowerCase();
  if (PERSONAL_EMAIL_DOMAINS.has(d)) return true;
  for (const suffix of SUFFIXES) {
    if (d === suffix || d.endsWith(`.${suffix}`)) return true;
  }
  return false;
}

export function isPersonalEmail(email: string): boolean {
  const e = email.trim().toLowerCase();
  const at = e.lastIndexOf("@");
  if (at < 0) return false;
  return isPersonalEmailDomain(e.slice(at + 1));
}
